config/routes.rb
Rails.application.routes.draw do

  root 'index#index'
  get 'oauth/authorize' => 'oauth#authorize', as: :oauth_authorize
  get 'oauth/callback' => 'oauth#callback', as: :oauth_callback

  get 'login' => 'sessions#new', as: :login
  delete 'logout' => 'sessions#destroy', as: :logout
  resources :sessions, :only => [:create]

  resources :trades do
    collection do
      get 'pickups' => 'trades#pickups', as: :pickups
    end
  end
  resources :banters
  get 'rosters/trade_form' => 'rosters#trade_form', as: :trades_roster
  resources :rosters, :only => [:index, :show]

  namespace :yahoo do
    get 'request/transactions' => 'request#transactions', as: :refresh_transactions
    get 'request/rosters' => 'request#rosters', as: :import_rosters
    get 'request/players' => 'request#players', as: :import_players
  end

  namespace :google do
    get 'request/read' => 'request#read', as: :read_spreadsheet
    get 'request/write_transaction' => 'request#write_transaction', as: :write_transaction
    get 'oauth/callback' => 'oauth#callback', as: :oauth_callback
    get 'oauth/authorize' => 'oauth#authorize', as: :oauth_authorize
  end

end

app/views/layouts/shared/_flash.html.erb
<% if flash[:notice] %>
    <p id='notice'><%= flash[:notice] %></p>
<%end%>
<% if flash[:alert] %>
    <p id='alert'><%= flash[:alert] %></p>
<%end%>
<% flash.clear if flash.present? %>

app/views/layouts/shared/_sidebar.html.erb
<div class="sidebar__header">
  <h2><%= link_to 'Keeperball', root_path %></h2>
</div>

<div class="sidebar__content">
  <ul class="sidebar__navigation">
    <li class="sidebar__navigation-element">
      <%= link_to "#{fa_icon('exchange')} Transactions".html_safe, trades_path %>
    </li>
    <li class="sidebar__navigation-element">
      <%= link_to "#{fa_icon('list-ul')} Rosters".html_safe, rosters_path %>
    </li>
    <li class="sidebar__navigation-element">
      <%= link_to "#{fa_icon('bullhorn')} Chirp".html_safe, banters_path %>
    </li>
  </ul>
</div>