config/routes.rb
Rails.application.routes.draw do

  root 'index#index'
  get 'oauth/authorize' => 'oauth#authorize', as: :oauth_authorize
  get 'oauth/callback' => 'oauth#callback', as: :oauth_callback

  get 'login' => 'sessions#new', as: :login
  delete 'logout' => 'sessions#destroy', as: :logout
  resources :sessions, :only => [:create]

  resources :trades do
    collection do
      get 'pickups' => 'trades#pickups', as: :pickups
    end
  end
  resources :banters
  get 'rosters/trade_form' => 'rosters#trade_form', as: :trades_roster
  resources :rosters, :only => [:index, :show]

  namespace :yahoo do
    get 'request/transactions' => 'request#transactions', as: :refresh_transactions
    get 'request/rosters' => 'request#rosters', as: :import_rosters
    get 'request/players' => 'request#players', as: :import_players
  end

  namespace :google do
    get 'request/read' => 'request#read', as: :read_spreadsheet
    get 'request/write_transaction' => 'request#write_transaction', as: :write_transaction
    get 'oauth/callback' => 'oauth#callback', as: :oauth_callback
    get 'oauth/authorize' => 'oauth#authorize', as: :oauth_authorize
  end

end

app/views/index/index.html.erb
<% title 'Home page' %>
<div class="yahoo-action-list">
<% if current_user.blank? %>
  <div class="action-set">
    <%= link_to 'login', login_path %>
  </div>
<% elsif current_user.yahoo_access_token.present? %>
    <h3>Yahoo League Actions:</h3>
    <div class="action-set">
      <%= link_to 'Import League Players', yahoo_import_players_path %>
    </div>
    <div class="action-set">
      <%= link_to 'Import League Teams', yahoo_import_rosters_path %>
    </div>
    <div class="action-set">
      <%= link_to 'Refresh League Transactions', yahoo_refresh_transactions_path %>
    </div>

    <h3>Google Sheet Actions:</h3>
    <div class="action-set">
      <%= link_to 'Read Rosters', google_read_spreadsheet_path %>
    </div>
    <div class="action-set">
      <%= link_to 'Write Rosters to Spreadsheet', google_write_transaction_path %>
    </div>
<% else %>
  <div class="action-set">
    <%= link_to 'Authorize Yahoo!', oauth_authorize_path %>
  </div>
<% end %>
</div>