config/routes.rb
Rails.application.routes.draw do

  root 'index#index'
  get 'oauth/authorize' => 'oauth#authorize', as: :oauth_authorize
  get 'oauth/callback' => 'oauth#callback', as: :oauth_callback

  get 'login' => 'sessions#new', as: :login
  delete 'logout' => 'sessions#destroy', as: :logout
  resources :sessions, :only => [:create]

  resources :trades do
    collection do
      get 'pickups' => 'trades#pickups', as: :pickups
    end
  end
  resources :banters
  get 'rosters/trade_form' => 'rosters#trade_form', as: :trades_roster
  resources :rosters, :only => [:index, :show]

  namespace :yahoo do
    get 'request/transactions' => 'request#transactions', as: :refresh_transactions
    get 'request/rosters' => 'request#rosters', as: :import_rosters
    get 'request/players' => 'request#players', as: :import_players
  end

  namespace :google do
    get 'request/read' => 'request#read', as: :read_spreadsheet
    get 'request/write_transaction' => 'request#write_transaction', as: :write_transaction
    get 'oauth/callback' => 'oauth#callback', as: :oauth_callback
    get 'oauth/authorize' => 'oauth#authorize', as: :oauth_authorize
  end

end

app/controllers/trades_controller.rb
class TradesController < ApplicationController
  before_action :find_trade, only: %i(accept decline show update)
  before_action :ensure_pending, only: %i(accept decline)

  def index
    @trades = Keeperball::Transaction.
      from_season(season).
      where(move_type: 'trade').
      order('completed_at ASC')
  end

  def pickups
    @trades = Keeperball::Transaction.
      from_season(season).
      where(move_type: 'add').
      order('completed_at ASC')
  end

  def show
  end

  def new
    @trade = Keeperball::Transaction.new
  end

  def create
    @trade = Keeperball::Transaction.new(
      move_type: 'trade',
      pending: true,
      transaction_key: current_year_key + '.custom_' + SecureRandom.uuid,
      completed_at: DateTime.now # TODO: get rid of this so we can have managers accept
    )

    processor = Keeperball::Transaction::Processor.new(@trade, trade_params)
    if processor.process && @trade.save
      redirect_to trades_path, notice: 'Trade Saved, notifying managers'
    else
      flash.now[:alert] =
        'Trade failed to save: ' +
        "#{@trade.errors.first.first.to_s} #{@trade.errors.first.second}"
      render :new
    end
  end

  def update
  end

  def propose
  end

  def decline
    if @trade.delete
      redirect_to trades_path,
                  notice: 'Trade Declined!'
    else
      redirect_to trade_path(@trade),
                  alert: ['Trade failed to save:',
                          @trade.errors.first.first.to_s,
                          @trade.errors.first.second].join(' ')
    end
  end

  def accept
    if @trade.update(pending: false)
      redirect_to trades_path,
                  notice: 'Trade Accepted! You just got fleeced you idiot'
    else
      redirect_to trade_path(@trade),
                  alert: ['Trade failed to save:',
                          @trade.errors.first.first.to_s,
                          @trade.errors.first.second].join(' ')
    end
  end

  private

  def trade_params
    params.permit(
      :from_team,
      :send_cap,
      :to_team,
      :get_cap,
      send_players: [],
      get_players: []
    )
  end

  def season
    (params[:season] || current_year).to_i
  end

  def find_trade
    @trade ||= Keeperball::Transaction.find(params[:id])
  end

  def ensure_pending
    unless @trade.pending?
      redirect_to trade_path(@trade),
                  alert: 'Cannot Accept or Decline a non-pending trade'
    end
  end
end

app/views/trades/_headings.html.haml
.page-heading
  %h1= content_for(:title)

.subheading-menu
  %ul.subheading-menu__list
    %li.subheading-menu__list-item{ class: ('subheading-menu__list-item--active' if current_page?(controller: 'trades', action: 'index')) }
      = link_to 'View all Trades', trades_path
    %li.subheading-menu__list-item
      = link_to 'View all Pickups', pickups_trades_path
    %li.subheading-menu__list-item{ class: ('subheading-menu__list-item--active' if current_page?(controller: 'trades', action: 'new')) }
      = link_to 'Propose a Trade', new_trade_path

app/views/trades/_player_fields.html.haml
- id = team_type == 'to' ? 'get_players' : 'send_players'
- label = team_type == 'to' ? 'Players to Receive' : 'Players to Trade Away'

.form-property{class: "form-property--#{id}"}
  .label.label--multi
    = label_tag id, label
  .selector.selector--multi
    = select_tag id, options_from_collection_for_select(roster.players, 'player_key', 'name'), multiple: true

app/views/trades/index.html.haml
- title 'All Trades'

= render 'trades/headings'

.main-container
  .trades-index-content
    .trades-table
      - @trades.each_with_index do |trade, i|
        .trades-table__trade_unit{ class: ('trades-table__trade_unit--even' if i % 2 == 0) }
          .trades-table__row
            .trades-table__row-cell.trades-table__row-cell--legend Date
            .trades-table__row-cell
              = trade.formatted_completed_date
          - trade.details_for_display.each do |dest_team, players|
            .trades-table__row
              .trades-table__row-cell.trades-table__row-cell--legend To
              .trades-table__row-cell
                %span= dest_team
              .trades-table__row-cell.trades-table__row-cell--players
                %span= players.join(', ')

app/views/trades/new.html.haml
- title 'New Trade'

= render 'trades/headings'

.main-container
  .trades-new-content
    .trades-new-form
      = form_tag trades_path, method: :post, id: 'new_trade_form' do
        .trades-new-form__form-section.trades-new-form__form-section--half-width
          .form-property
            .label
              = label_tag 'from_team', 'Your Team'
            .selector
              = select_tag 'from_team', options_from_collection_for_select(Keeperball::Roster.all, 'team_key', 'name'), data: { from_team_trigger: '' }

          .form-group--from-team{ data: { from_team_fields: '' } }
            = render 'trades/player_fields', roster: Keeperball::Roster.first, team_type: 'from'

          .form-property
            .label
              = label_tag 'send_cap', 'Send Cap'
            .selector
              = number_field_tag 'send_cap', 0

        .trades-new-form__form-section.trades-new-form__form-section--half-width
          .form-property
            .label
              = label_tag 'to_team', 'Their Team'
            .selector
              = select_tag 'to_team', options_from_collection_for_select(Keeperball::Roster.all, 'team_key', 'name'), data: { to_team_trigger: '' }

          .form-group--to-team{ data: { to_team_fields: '' } }
            = render 'trades/player_fields', roster: Keeperball::Roster.first, team_type: 'to'

          .form-property
            .label
              = label_tag 'get_cap', 'Get Cap'
            .selector
              = number_field_tag 'get_cap', 0

        .trades-new-form__form-section.trades-new-form__form-section--full-width
          .button-container
            = button_tag 'submit'

app/views/trades/pickups.html.haml
- title 'All Trades'

= render 'trades/headings'

.main-container
  .trades-index-content
    .trades-table
      - @trades.each_with_index do |trade, i|
        .trades-table__trade_unit{ class: ('trades-table__trade_unit--even' if i % 2 == 0) }
          .trades-table__row
            .trades-table__row-cell.trades-table__row-cell--legend
              %span Date
            .trades-table__row-cell
              %span= trade.formatted_completed_date
          .trades-table__row
            .trades-table__row-cell.trades-table__row-cell--legend
              %span Source
            .trades-table__row-cell
              %span= trade.pickup_type
          - trade.pickup_details_for_display.each do |dest_team, players|
            .trades-table__row
              .trades-table__row-cell.trades-table__row-cell--legend
                %span To
              .trades-table__row-cell
                %span= dest_team
              .trades-table__row-cell.trades-table__row-cell--players
                %span= players.join(', ')